In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/murpi/wilddata/master/pokemon.csv')
df

#            Name   Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0      1       Bulbasaur    Grass  Poison  45      49       49       65   
1      2         Ivysaur    Grass  Poison  60      62       63       80   
2      3        Venusaur    Grass  Poison  80      82       83      100   
3      4   Mega Venusaur    Grass  Poison  80     100      123      122   
4      5      Charmander     Fire     NaN  39      52       43       60   
..   ...             ...      ...     ...  ..     ...      ...      ...   
795  796         Diancie     Rock   Fairy  50     100      150      100   
796  797    Mega Diancie     Rock   Fairy  50     160      110      160   
797  798  Hoopa Confined  Psychic   Ghost  80     110       60      150   
798  799   Hoopa Unbound  Psychic    Dark  80     160       60      170   
799  800       Volcanion     Fire   Water  80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
0         65     45           1      False  
1         80     60           1      False  
2        100     80           1      False  
3        120     80           1      False  
4         50     65           1      False  
..       ...    ...         ...        ...  
795      150     50           6       True  
796      110    110           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True  

[800 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64 
 5   Attack      800 non-null    int64 
 6   Defense     800 non-null    int64 
 7   Sp. Atk     800 non-null    int64 
 8   Sp. Def     800 non-null    int64 
 9   Speed       800 non-null    int64 
 10  Generation  800 non-null    int64 
 11  Legendary   800 non-null    bool  
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB


In [ ]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
#df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
team = ['Mewtwo', 'Lugia', 'Rayquaza', 'Dialga','Palkia', 'Giratina Altered Forme']

""" pour trouver le pokemon Giratina """
team_data = df[df['Name'].str.contains('Giratina')]

""" extraine un des deux et le coller dans la liste """

team_data = df[df['Name'].isin(team)]
team_data

#                    Name   Type 1  Type 2   HP  Attack  Defense  \
162  163                  Mewtwo  Psychic     NaN  106     110       90   
269  270                   Lugia  Psychic  Flying  106      90      130   
425  426                Rayquaza   Dragon  Flying  105     150       90   
540  541                  Dialga    Steel  Dragon  100     120      120   
541  542                  Palkia    Water  Dragon   90     120      100   
544  545  Giratina Altered Forme    Ghost  Dragon  150     100      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
162      154       90    130           1       True  
269       90      154    110           2       True  
425      150       90     95           3       True  
540      150      100     90           4       True  
541      150      120    100           4       True  
544      100      120     90           4       True

In [ ]:
team_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 162 to 544
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           6 non-null      int64 
 1   Name        6 non-null      object
 2   Type 1      6 non-null      object
 3   Type 2      5 non-null      object
 4   HP          6 non-null      int64 
 5   Attack      6 non-null      int64 
 6   Defense     6 non-null      int64 
 7   Sp. Atk     6 non-null      int64 
 8   Sp. Def     6 non-null      int64 
 9   Speed       6 non-null      int64 
 10  Generation  6 non-null      int64 
 11  Legendary   6 non-null      bool  
dtypes: bool(1), int64(8), object(3)
memory usage: 582.0+ bytes


In [ ]:
from sklearn.neighbors import NearestNeighbors

""" on recupere la liste des colonnes numeriques """

X = df[['HP',	'Attack','Defense','Sp. Atk','Sp. Def','Speed','Generation']]

""" on entraine sur une varaiable """
distance = NearestNeighbors(n_neighbors = 6).fit(X)

""" on affiche les plus proches voisins """
distance.kneighbors()

(array([[11.18033989, 14.6628783 , 17.        , 17.49285568, 18.97366596,
         19.02629759],
        [10.63014581, 11.66190379, 13.52774926, 20.71231518, 20.71231518,
         21.72556098],
        [19.89974874, 20.34698995, 20.34698995, 21.79449472, 22.737634  ,
         23.        ],
        ...,
        [39.9374511 , 43.69210455, 44.19275959, 48.18713521, 48.98979486,
         51.        ],
        [50.08991915, 54.77225575, 60.07495318, 62.12084996, 64.81512169,
         64.83826031],
        [28.08914381, 29.30870178, 32.03123476, 34.6121366 , 34.69870315,
         37.46998799]]),
 array([[643, 438, 762, 294,  59,  48],
        [308, 644, 439, 722, 636, 391],
        [645, 201, 249,  60, 295, 252],
        ...,
        [  8, 421, 306, 518, 776, 706],
        [422, 797, 420, 425, 706, 541],
        [ 12, 366, 542,   3, 538, 540]]))

In [ ]:
""" on affiche les colonnes des variables X de la tean data """
distance_pkmn, index_pkmn = distance.kneighbors(team_data[X.columns])

In [ ]:
""" distance """

distance_pkmn

array([[ 0.        , 41.34005322, 42.22558466, 43.08131846, 45.36518489,
        45.50824101],
       [ 0.        , 46.10856753, 47.07440918, 51.30302135, 51.70106382,
        57.90509477],
       [ 0.        , 34.69870315, 35.73513677, 35.73513677, 36.74234614,
        42.47352116],
       [ 0.        , 28.3019434 , 31.6227766 , 36.51027253, 37.40320842,
        37.46998799],
       [ 0.        , 14.17744688, 20.02498439, 31.60696126, 31.6227766 ,
        33.18132005],
       [ 0.        , 40.        , 50.49752469, 50.99019514, 52.72570531,
        57.48043145]])

In [ ]:
"""
index des lignes qui nous interessent, attention a bie prendre les pokemons non legendaires
ici on s'intéresse a la colonnes 2, elle correspond à la colonne des voisins les plus proches
pour chacun des 6 pokemon de la liste testés.
si le pokemon voisin est un legendaire passer à celui d'à coté.

"""

index_pkmn

array([[162, 551, 248, 275, 712,  23],
       [269, 546, 537, 264, 156, 417],
       [425, 710, 792, 793, 279, 712],
       [540, 706, 541,  12,   7, 799],
       [541, 706, 420,   8, 540, 421],
       [544, 545, 546, 552, 794, 264]])

In [ ]:
df_index = pd.DataFrame(index_pkmn)
df_index

0    1    2    3    4    5
0  162  551  248  275  712   23
1  269  546  537  264  156  417
2  425  710  792  793  279  712
3  540  706  541   12    7  799
4  541  706  420    8  540  421
5  544  545  546  552  794  264

In [ ]:
"""
ci dessous les 6 pokemons a proposer au joueur
par contre il faut trouver un moyer de boucler dans la colonne 2 de l'array index_pkmn

"""


In [ ]:
df[df.index == 248]

#           Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
248  249  Mega Houndoom   Dark   Fire  75      90       90      140       90   

     Speed  Generation  Legendary  
248    115           2      False

In [ ]:
df[df.index == 546]

#       Name   Type 1 Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  \
546  547  Cresselia  Psychic    NaN  120      70      120       75      130   

     Speed  Generation  Legendary  
546     85           4      False

In [ ]:
df[df.index == 279]

#           Name Type 1    Type 2  HP  Attack  Defense  Sp. Atk  \
279  280  Mega Blaziken   Fire  Fighting  80     160       80      130   

     Sp. Def  Speed  Generation  Legendary  
279       80    100           3      False

In [ ]:
df[df.index == 12]

#            Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
12  13  Mega Blastoise  Water    NaN  79     103      120      135      115   

    Speed  Generation  Legendary  
12     78           1      False

In [ ]:
df[df.index == 8]

#              Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
8  9  Mega Charizard Y   Fire  Flying  78     104       78      159      115   

   Speed  Generation  Legendary  
8    100           1      False

In [ ]:
df[df.index == 546]

#       Name   Type 1 Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  \
546  547  Cresselia  Psychic    NaN  120      70      120       75      130   

     Speed  Generation  Legendary  
546     85           4      False